FROM node:16-alpine AS builder
WORKDIR /app
COPY . .
RUN npm install -g serve

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"] 