# src/main/resources/application-dev.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventgraph_to_text?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12345678

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678
